theme: jekyll-theme-slate

lang: es
title: Lovecraft
description: Relatos de horror cósmico clásicos y actuales.

url: https://carleslc.me/Lovecraft/

author:
  name: Carleslc
  url: https://github.com/Carleslc
